name: pull_branch

on:
  workflow_dispatch:

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Make script executable
      run: chmod +x prod-to-dev-script.sh

    - name: Execute script
      run: |
        set -e
        ./prod-to-dev-script.sh
      shell: bash