name: pull_branch

on:
  workflow_dispatch:

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout prod branch
      uses: actions/checkout@v4
      with:
        ref: prod

    - name: Make script executable
      run: chmod +x dev-to-prod-script.sh

    - name: Execute script
      run: ./dev-to-prod-script.sh
      shell: bash
